aula/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include("cliente.urls")),
]

cliente/urls.py
from django.urls import path
from . import views

app_name="cliente"

urlpatterns = [
    path("", views.index , name="index" ),
    path("cadastro/", views.cadastro, name="cadastro"),
    path("busca/", views.busca, name="busca"),
    path("busca/<int:cliente>", views.busca, name="buscaum"),
]

cliente/models.py
from django.db import models

# Create your models here.

class Genero(models.Model):
    nm_genero = models.CharField(verbose_name="Gênero",max_length=10)
    sg_genero = models.CharField(verbose_name="Abrev. gênero",max_length=4)



class Cliente(models.Model):
    nome = models.CharField(verbose_name="Nome",max_length=45)
    cpf = models.CharField(verbose_name="CPF",max_length=14)
    fk_genero = models.ForeignKey(Genero, on_delete=models.CASCADE, verbose_name= "Gênero", default=0)
    telefone = models.CharField(verbose_name="Telefone",max_length=14)
    idade = models.IntegerField(verbose_name="Idade")

cliente/forms.py
from django import forms
from .models import Genero

class GeneroForm(forms.ModelForm):
    class Meta:
        model = Genero
        fields = "__all__"

cliente/views.py
from django.shortcuts import render
from django.http import HttpResponse
from cliente.models import Genero

#Formulários

from .forms import GeneroForm

#Views

def index(request):

    context = {} #{"nome":"Batman"}

    return render(request, "cliente/index.html", context)

def cadastro(request):

    if request.method == "GET":
        form = GeneroForm()
        context = { 
            "form" : form,
        }
        return render(request, "cliente/cadastroGenero.html", context)
    
    elif request.method == "POST":
    
        form = GeneroForm( request.POST )
        form.save()

        context = { 
            "sucesso" : "Gênero cadastrado com sucesso",
        }

        return render(request, "cliente/cadastroGenero.html", context)
    
    else: 
        return HttpResponse("<h2>Tá errado issaí</h2>")


def busca(request, cliente=0):

    busca = Genero.objects.all()

    context= {
        "generos":busca,
    }

    return render(request, "cliente/buscaGenero.html", context)

cliente/templates/cliente/base.html
<html>
    <head>
        <title>
        {% block title %}    
            Meu Sistema 
        {% endblock title %}
        </title>

        <!-- Inserir link bootstrap -->

        {% block css %}
        {% endblock css %}

        <!-- Inserir link javascript e jquery-->

        {% block js %}
        {% endblock js %}       

    </head> 
    <body>
        
        <div class="container">
            {% block conteudo %}
            {% endblock conteudo %}
        </div>

    </body>
</html>

cliente/templates/cliente/buscaGenero.html
{% extends 'cliente/base.html' %}

    {% block title %}
        Meu sistema - Busca Gênero
    {% endblock title %}

    {% block conteudo %}
        {% if generos %}
            <table>
                <tr>
                    <td> Gênero </td>
                    <td> Abreviatura </td>
                </tr>
                    {% for genero in generos %}
                        <tr>
                            <td>{{ genero.nm_genero }}</td> 
                            <td>{{ genero.sg_genero }}</td>
                        </tr>
                    {% endfor %}
            </table>
        {% endif %}
    {% endblock conteudo %}  

cliente/templates/cliente/cadastroGenero.html
{% extends 'cliente/base.html' %}

{% load crispy_forms_tags %}

    {% block title %}
        Meu Sistema - Cadastro de Gênero
    {% endblock title %}


    {% block conteudo %} 
        {% if sucesso %}
            <div class="alert alert-sucess">{{ sucesso }}</div>
        {% endif %}
        
        {% if form %}
        <form action="{% url 'cliente:cadastro' %}" method="POST">
            
            <div class="row">
                <div class="col-6" >
                    {{ form.nm_genero|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-6" >
                    {{ form.sg_genero|as_crispy_field }}
                </div>
            </div>

            
            <input class="btn btn-primary" type="submit" value ="Vai" />

        </form>
        {% endif %}
    {% endblock conteudo %}

cliente/templates/cliente/erro.html
<div class="alert alert-info"> Sou uma mensagem de informação incluída </div>

cliente/templates/cliente/index.html
{% extends 'cliente/base.html' %}

    {% block conteudo %}
        {% if erro %}
            {% include 'cliente/erro.html' with erro=erro %}          
        {% endif %}
        <p> Sou o index </p>
    {% endblock conteudo %}

              